import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { Payment } from "@/hooks/usePayments";
import { format } from "date-fns";

interface ExportPaymentsProps {
  payments: Payment[];
  totals: {
    sent: number;
    received: number;
    balance: number;
  };
}

const ExportPayments = ({ payments, totals }: ExportPaymentsProps) => {
  const exportToDocument = () => {
    // Create formatted document content
    const lines = [
      "PAIRENT - PAYMENT RECORDS EXPORT",
      "=" .repeat(50),
      "",
      `Export Date: ${format(new Date(), "MMMM d, yyyy 'at' h:mm a")}`,
      "",
      "SUMMARY",
      "-".repeat(50),
      `Total Sent:     $${totals.sent.toFixed(2)}`,
      `Total Received: $${totals.received.toFixed(2)}`,
      `Balance:        ${totals.balance >= 0 ? "+" : ""}$${totals.balance.toFixed(2)} ${totals.balance >= 0 ? "(In your favor)" : "(Owed)"}`,
      "",
      "",
      "TRANSACTION HISTORY",
      "-".repeat(50),
      "",
    ];

    // Add each transaction
    payments.forEach((payment) => {
      const date = format(new Date(payment.created_at), "MMM d, yyyy 'at' h:mm a");
      const type = payment.type.toUpperCase();
      const amount = `${payment.type === "sent" ? "-" : "+"}$${Number(payment.amount).toFixed(2)}`;
      
      lines.push(`Date:        ${date}`);
      lines.push(`Type:        ${type}`);
      lines.push(`Amount:      ${amount}`);
      lines.push(`Description: ${payment.description}`);
      lines.push(`Status:      ${payment.status.toUpperCase()}`);
      lines.push("-".repeat(50));
      lines.push("");
    });

    // Add footer
    lines.push("");
    lines.push("This document was generated by Pairent Co-Parenting App");
    lines.push(`Total Transactions: ${payments.length}`);

    // Create and download file
    const content = lines.join("\n");
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `pairent-payment-records-${format(new Date(), "yyyy-MM-dd")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const exportToCSV = () => {
    // Create CSV content
    const headers = ["Date", "Type", "Amount", "Description", "Status"];
    const rows = payments.map((payment) => {
      const date = format(new Date(payment.created_at), "yyyy-MM-dd HH:mm:ss");
      const type = payment.type;
      const amount = Number(payment.amount).toFixed(2);
      const description = `"${payment.description.replace(/"/g, '""')}"`;
      const status = payment.status;
      
      return [date, type, amount, description, status].join(",");
    });

    // Add summary at the end
    const summary = [
      "",
      "SUMMARY",
      `Total Sent,${totals.sent.toFixed(2)}`,
      `Total Received,${totals.received.toFixed(2)}`,
      `Balance,${totals.balance.toFixed(2)}`,
    ];

    const csvContent = [headers.join(","), ...rows, ...summary].join("\n");

    // Create and download file
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `pairent-payment-records-${format(new Date(), "yyyy-MM-dd")}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex gap-2">
      <Button
        variant="outline"
        onClick={exportToDocument}
        className="gap-2"
        disabled={payments.length === 0}
      >
        <Download className="w-4 h-4" />
        Export as Text
      </Button>
      <Button
        variant="outline"
        onClick={exportToCSV}
        className="gap-2"
        disabled={payments.length === 0}
      >
        <Download className="w-4 h-4" />
        Export as CSV
      </Button>
    </div>
  );
};

export default ExportPayments;
